### ISSUE TITLE
How to fine-tune LoRA of LLaMA-3.2 11B Vision using raw text dataset?

### ISSUE THREAD

**Issue by yukiarimo** [2U1/Llama3.2-Vision-Finetune#17]
Hello. I have the dataset like this in the JSONL format:

```
{“text”: “my chunk 1”}
{“text”: “my chunk 2”}
```

Using this repo (or whatever available) how can I:
1. Fine-tune LoRA/QLoRA (with all modules included) for the text only model using this raw text?
2. Fine-tune both text+vision using the same stuff but like `{“text”: “Q: Who is this <data>{image_tokens}</data>\nA: This is you!”}`

**Comment by 2U1** [comment]
You could just format the data written in the readme.
Also, the image should be at the first of the text (LLama3.2-vision only supports the data like that).

However, the data that are mixed (something has image+text , something only has text) dosen't work for now so it need to be a bit fixed.

**Comment by yukiarimo** [comment]
Closing this cause unsloth released support for it!
