### ISSUE TITLE
Training time and Data format support

### ISSUE THREAD

**Issue by LeslieTrue** [2U1/Llama3.2-Vision-Finetune#2]
Hi dude, nice code base!
I have a few questions regarding the training time and want to double check with you. 

I'm training the llama-3.2-vision-instruct-11B model on a customized dataset with full-finetuning scripts. 
Devices: 8*A800 (equivalent speed with A100)
Batch size: 8*8
Num samples: 200k
Avg length of samples: 252 tokens

It takes me~10 hours to finish training. I'm wondering if it's normal. 
As usual, it takes 3 hours to train a 7-8B MLLM. I assume that inference llama-3.2 takes more compute but I'm not quite sure about it.

Also, would you mind adding support of language-only data loading in your codebase?

`deepspeed --include=localhost:0,1,2,3,4,5,6,7 src/training/train.py \
    --deepspeed scripts/zero3_offload.json \
    --model_id $MODEL_NAME \
    --data_path balabala \
    --image_folder balabala \
    --disable_flash_attn2 True \
    --lora_enable False \
    --tune_img_projector True \
    --freeze_vision_tower False \
    --freeze_llm False \
    --bf16 True \
    --output_dir output/test_vision_v3 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --learning_rate 1e-5 \
    --projector_lr 1e-5 \
    --vision_lr 2e-6 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --gradient_checkpointing True \
    --report_to wandb \
    --lazy_preprocess True \
    --save_strategy "steps" \
    --save_steps 10 \
    --save_total_limit 10 \
    --dataloader_num_workers 4`

**Comment by 2U1** [comment]
It can be the issue of flash-attention for the time. Cuz llama3.2-vision dosen't support flash-attention for now. 

For the text-only data, I'll make a update for it. Thanks for the feedback.

**Comment by 2U1** [comment]
Need to fix the attention code in the model code directly or do a monkey patch. But it's a bit hard job for it.

**Comment by 2U1** [comment]
@LeslieTrue I've updated the code to support text-only data too.
