### ISSUE TITLE
 missing 1 required positional argument: 'processor'

### ISSUE THREAD

**Issue by NandhaKishorM** [2U1/Llama3.2-Vision-Finetune#3]
when I run 
bash scripts/finetune_lora_vision.sh

/Llama3.2-Vision-Finetune/src/training/data.py", line 280, in make_supervised_data_module
    data_collator = DataCollatorForSupervisedDataset(pad_token_id=processor.tokenizer.pad_token_id)
TypeError: __init__() missing 1 required positional argument: 'processor'

**Comment by 2U1** [comment]
@NandhaKishorM Sorry for the inconvinience. I've updated the code. 
I made a mistake when updating the code last night.

You could update use the newest code or update your code by
`data_collator = DataCollatorForSupervisedDataset(pad_token_id=processor.tokenizer.pad_token_id, processor=processor)` in data.py

It's almost the last line in the data.py.

**Comment by NandhaKishorM** [comment]
kinda stuck at
Adding LoRA to the model...

it is not moving from here

**Comment by NandhaKishorM** [comment]
data.py", line 201, in __call__
    if cross_attention_mask is not None:
UnboundLocalError: local variable 'cross_attention_mask' referenced before assignment

**Comment by 2U1** [comment]
@NandhaKishorM Sorry, I've updated once more. But, I'm not sure if the mixed data, like share-GPT works properly.

**Comment by NandhaKishorM** [comment]
its single image data in json(llava format).  Now comes a new error
data.py", line 213, in __call__
    pixel_values = torch.cat([pv for pv in batch_pixel_values if pv is not None], dim=0) if any(batch_pixel_values) else None
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by 2U1** [comment]
```
        pixel_values = torch.cat([pv for pv in batch_pixel_values if pv is not None and pv.numel() > 0], dim=0) if any(pv is not None and pv.numel() > 0 for pv in batch_pixel_values) else None
        aspect_ratio_ids = torch.cat([ar for ar in batch_aspect_ratio_ids if ar is not None and ar.numel() > 0], dim=0) if any(ar is not None and ar.numel() > 0 for ar in batch_aspect_ratio_ids) else None
        aspect_ratio_mask = torch.cat([am for am in batch_aspect_ratio_mask if am is not None and am.numel() > 0], dim=0) if any(am is not None and am.numel() > 0 for am in batch_aspect_ratio_mask) else None
```

You can fix your 3 lines in data.py 
It is in Datacollator part.

**Comment by NandhaKishorM** [comment]
class DataCollatorForSupervisedDataset(object):
    """Collate examples for supervised fine-tuning."""

    def __init__(self, pad_token_id: int, processor: transformers.ProcessorMixin):
        self.pad_token_id = pad_token_id
        self.processor = processor

    def __call__(self, examples):
        batch_input_ids = []
        batch_label_ids = []
        batch_pixel_values = []
        batch_aspect_ratio_ids = []
        batch_aspect_ratio_mask = []
        batch_cross_attention_mask = []

        for example in examples:
            batch_input_ids.append(example["input_ids"])
            batch_label_ids.append(example["labels"])
            batch_pixel_values.append(example.get("pixel_values"))
            batch_aspect_ratio_ids.append(example.get("aspect_ratio_ids"))
            batch_aspect_ratio_mask.append(example.get("aspect_ratio_mask"))
            batch_cross_attention_mask.append(example.get("cross_attention_mask"))
                
        input_ids = pad_sequence(
            batch_input_ids, padding_side='right', padding_value=self.pad_token_id
        )

        if not all(item is None for item in batch_cross_attention_mask):
            batch_cross_attention_mask = [cam for cam in batch_cross_attention_mask if cam is not None]
            cross_attention_mask = pad_sequence(
                batch_cross_attention_mask, padding_side='right', padding_value=0
            )
        else:
            cross_attention_mask = None
        
        labels = pad_sequence(
            batch_label_ids, padding_side='right', padding_value=IGNORE_INDEX
        )
        
        attention_mask = input_ids != self.pad_token_id

        # Fix for pixel_values concatenation
        pixel_values = torch.cat([pv for pv in batch_pixel_values if pv is not None and pv.numel() > 0], dim=0) if any(pv is not None and pv.numel() > 0 for pv in batch_pixel_values) else None
        
        # Similar fixes for aspect_ratio_ids and aspect_ratio_mask
        aspect_ratio_ids = torch.cat([ar for ar in batch_aspect_ratio_ids if ar is not None and ar.numel() > 0], dim=0) if any(ar is not None and ar.numel() > 0 for ar in batch_aspect_ratio_ids) else None
        aspect_ratio_mask = torch.cat([am for am in batch_aspect_ratio_mask if am is not None and am.numel() > 0], dim=0) if any(am is not None and am.numel() > 0 for am in batch_aspect_ratio_mask) else None

        batch_dict = dict(
            input_ids=input_ids,
            labels=labels,
            attention_mask=attention_mask,
        )

        if pixel_values is not None:
            batch_dict['pixel_values'] = pixel_values
            batch_dict['aspect_ratio_ids'] = aspect_ratio_ids
            batch_dict['aspect_ratio_mask'] = aspect_ratio_mask
            batch_dict['cross_attention_mask'] = cross_attention_mask

        return batch_dict
 this works

**Comment by 2U1** [comment]
Sorry for the inconvinience. I made some mistake when making text-only data support.
