### ISSUE TITLE
RuntimeError: The expanded size of the tensor (448) must match the existing size (446) at non-singleton dimension 2.  Target sizes: [1, 32, 448, 38424].  Tensor sizes: [1, 1, 446, 38424]

### ISSUE THREAD

**Issue by chuan573906361** [2U1/Llama3.2-Vision-Finetune#6]
After installation, when I run bash finetune_lora.sh,the error:
  File "/home/jinchuan/anaconda3/envs/llama3v/lib/python3.10/site-packages/transformers/models/mllama/modeling_mllama.py", line 650, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: The expanded size of the tensor (448) must match the existing size (446) at non-singleton dimension 2.  Target sizes: [1, 32, 448, 38424].  Tensor sizes: [1, 1, 446, 38424]
is there any solution ?

**Comment by 2U1** [comment]
1. Does your dataset has mixed modality?
2. Did you follow the dataset format?

**Comment by chuan573906361** [comment]
Thanks for the response.I used a multi-images dataset. I think this is the main reason of the error above.And I finetune my dataset successfully using Phi-3.5 vision project.Thanks for your excellent work again.

**Comment by 2U1** [comment]
@chuan573906361 Thanks for the issue.
I'll try to fix it asap.

**Comment by CynthiaChuang** [comment]
Hi, @2U1 
I encountered a similar error,
```
attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: The expanded size of the tensor (188) must match the existing size (187) at non-singleton dimension 2.
Target sizes: [1, 32, 188, 6404].  Tensor sizes: [1, 1, 187, 6404]
```
 but my dataset is not a mixed dataset; it's a single dataset that was previously used for [Phi3-Vision-Finetune.](https://github.com/2U1/Phi3-Vision-Finetune) 
 
 ```
 [
    {
        "id": "011e7e629fb9ae7b",
        "image": "textvqa/train_images/011e7e629fb9ae7b.jpg",
        "conversations": [
            {
                "from": "human",
                "value": "<image>\nProvide a one-sentence caption for the provided image.\nReference OCR token: LESS, IN, LESS, IN, SE, TENSE, ZERO, ALHC, ZERO, ALDL, LESS, INTENSE, $S, INTENSE, COHOL, RO, ALCOHOL, ZERO, ALCOHOL, LISTER, ERINE, ZER, LISTER, ZER, LISTERINE, ZERO, STERINE, ERO, MOUTHW, ProventoKill, MOUTHW, ZERO, MOUTH, Millions, Proven, illMillions, Contact, Germs, MOUTHWAS, ermstha, Cause, Breathon, Proven, Kill, Millions, Germs, CLEANMINT, Breath, Contact, CLEANMINT"
            },
            {
                "from": "gpt",
                "value": "Five Listerine Zero mouthwash bottles on a store shelf."
            }
        ]
    },
    ....
  ]
 ```
 
 Uh... their dataset format should be the same, right?

**Comment by 2U1** [comment]
@CynthiaChuang Yes it should be the same as th Phi3.
I'll check this one. I think it's caused by the cross-attention from the processor.

**Comment by CynthiaChuang** [comment]
May I ask if you have a working dataset on hand? Could you share a sample for me to try? Although I don't think it's an issue with my dataset format, I'd like to rule out this factor. Thank you!

**Comment by 2U1** [comment]
@CynthiaChuang 
I'm using the dataset like this

```json
  {
    "id": "8fa37cb9-b4389b66",
    "image": "bdd100k/images/100k/train/8fa37cb9-b4389b66.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nConsidering the image, what might be the impact of the traffic conditions on the city's economy and environment?"
      },
      {
        "from": "gpt",
        "value": "The image shows a congested urban street with heavy traffic, including a large truck and multiple vehicles, which could indicate inefficiencies in the city's transportation system. This congestion can lead to increased fuel consumption and emissions, contributing to environmental pollution and potentially affecting public health. The economic impact includes lost productivity due to delays, increased operational costs for businesses, and possibly higher insurance premiums. The presence of pedestrians and the proximity to commercial buildings suggest that the congestion could also affect the local economy by deterring customers and reducing the attractiveness of the area for investment. Furthermore, the traffic conditions might influence the city's planning and infrastructure development, as it highlights the need for better traffic management and possibly more public transportation options to alleviate the congestion and its negative effects."
      }
    ]
  },
 ```
 
 I gotta find out what cuases the error. I just checked with LoRA and it wasn't happening.

**Comment by 2U1** [comment]
@chuan573906361 @CynthiaChuang 
It looks like it problem of batching. I'll try to fix it. The code should work with batchsize = 1

**Comment by CynthiaChuang** [comment]
@2U1 
Three pieces of information for your reference
1. The dataset format you provided still cannot be executed, so we can rule out the dataset issue.
2. I tested with a batch size of 1 earlier, but it still doesn't work.
3. Provide my execution parameters for your reference:

```
ENV_OUTPUT_DIR=/workspace/output/tmp
ENV_MODEL_ID=/workspace/Llama-3.2-11B-Vision-Instruct
ENV_BATCH=1
ENV_GRADIENR_ACCUMLATION=1
ENV_MAX_SEQ_LEN=131072
#ENV_MAX_SEQ_LEN=32768
ENV_EPOCHS=1
ENV_TUNE_IMG_PROJECTOR=True
ENV_GFEEZE_VISION_TOWER=False
ENV_FREEZE_LLM=False
ENV_LEARNING_RATE=5E-5
ENV_DATA_PATH=/workspace/llava_dataset/archive_json/small_test/tmp.json
ENV_DEEPSPEED=/workspace/Llama3.2-Vision-Finetune/scripts/zero3.json
ENV_IMAGE_FOLDER=/workspace/llava_dataset/
ENV_SAVE_STEPS=1000

PYTHONPATH=$PYTHONPATH:"/workspace/Llama3.2-Vision-Finetune/src/" 

/workspace/Llama3.2-Vision-Finetune/src/training/train.py \
    --deepspeed $ENV_DEEPSPEED \
    --model_id $ENV_MODEL_ID \
    --data_path $ENV_DATA_PATH \
    --image_folder $ENV_IMAGE_FOLDER \
    --tune_img_projector $ENV_TUNE_IMG_PROJECTOR \
    --freeze_vision_tower $ENV_GFEEZE_VISION_TOWER \
    --bf16 False \
    --output_dir $ENV_OUTPUT_DIR \
    --num_train_epochs $ENV_EPOCHS \
    --per_device_train_batch_size $ENV_BATCH \
    --gradient_accumulation_steps $ENV_GRADIENR_ACCUMLATION \
    --learning_rate $ENV_LEARNING_RATE \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --tf32 False \
    --gradient_checkpointing True \
    --report_to none \
    --lazy_preprocess True \
    --dataloader_num_workers 4 \
    --disable_flash_attn2 True \
    --save_steps $ENV_SAVE_STEPS \
    --max_seq_length $ENV_MAX_SEQ_LEN \
    --freeze_llm $ENV_FREEZE_LLM
    ```

**Comment by 2U1** [comment]
I have not enough to unfrezze all the module for full-finetuning. So I've tested with only unfreezing the llm or vision_model. But it works well for me.
However I've used zero2 becuase, when using zero3, I only get lr=0 for now.

**Comment by 2U1** [comment]
@CynthiaChuang May be you can try the latest code I merged the PR.

**Comment by CynthiaChuang** [comment]
@2U1 
Sure, I will give it a try this afternoon and get back to you once I have results.

**Comment by CynthiaChuang** [comment]
Hi, @2U1 

I quickly tested the new code using the zero3_offload setting, and the message didn’t appear again. 

However, I haven’t completed testing the zero3 part yet. The image tokens in llama3.2 have increased significantly, so I encountered an OOM (Out of Memory) error. Once I can borrow a more powerful machine to complete this part of the testing, I will report back
